apiVersion: v1
kind: Pod
metadata:
  name: my-config-pod
  labels:
    name: my-config-pod
spec:
  containers:
  - name: my-config-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    envFrom:
      - configMapRef: #If you want to inject the entire configMap
          name: my-first-configmap

# the below section shows how to read a specific key from a configMap

    env:
      - name: app_color
        valueFrom:
           configMapKeyRef:
              name: my-first-configmap
              key: app_color
