apiVersion: v1
kind: ReplicationController
metadata:
  name: myfirst-rc
spec:
  replicas: 4
  template:
    metadata:
      name: pod-yaml
      labels:
        name: pod-yaml
        tier: frontend
    spec:
      containers:
        - name: yaml-container
          image: nginx


  