apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  DB_Host: bG9jYWxob3N0
  DB_User: amlieWpvamU=
  DB_password: bm90c29zZWNyZXQ=

# Note: Please refer the secret-pod.yaml file to see how this secret has been injected to the pod.